Repository Requisitos-de-Software/2022.2-LinkedIn, pull requests merged in 2022-11, with the labels that each got.

#4 entrega-etapa-1
  README.md
  docs/assets/richPictures/Dados.png
  docs/assets/richPictures/EmpresasAtor.png
  docs/assets/richPictures/LimitesDoSistema.png
  docs/assets/richPictures/Operacao.png
  docs/assets/richPictures/RichPicture1.jpg
  docs/assets/richPictures/RichPicture2.png
  docs/assets/richPictures/Seta.png
  docs/assets/richPictures/UsuarioAtor.png
  docs/assets/richPictures/UsuariosAtor.png
  docs/index.md
  docs/planejamento/analise-app.md
  docs/planejamento/cronograma.md
  docs/planejamento/ferramentas.md
  docs/planejamento/metodologias.md
  docs/preRastreabilidade/rich-picture.md
  docs/preRastreabilidade/richPicture.md
  mkdocs.yml
Labels: entrega1

#5 Inclusão de ferramentas utilizadas
  docs/planejamento/ferramentas.md
Labels: documentation, entrega1

#6 Inclusão de ferramentas
  docs/planejamento/ferramentas.md
Labels: entrega1

#12 Inclusão da apresentação 1
  docs/apresentacoes/apresentacoes.md
Labels: entrega1

#19 Adicionando parte da Observação
  docs/assets/personas/antipersona.png
  docs/assets/personas/persona1.png
  docs/assets/personas/persona2.png
  docs/assets/personas/persona3.png
  docs/elicitacao/observacao.md
  docs/elicitacao/personas.md
  mkdocs.yml
Labels: documentation, entrega2

#17 Adiciona a entrevista no tópico de elicitação
  docs/elicitacao/entrevistas.md
  mkdocs.yml
Labels: documentation, entrega2

#18 Elaboração do artefato de brainstorm
  docs/elicitacao/brainstorm.md
  mkdocs.yml
Labels: documentation, entrega2

#20 correções nas estruturas do projeto e alterações nos artefatos
  docs/elicitacao/entrevistas.md
  docs/elicitacao/observacao.md
  docs/elicitacao/personas.md
  docs/elicitacao/storytelling.md
  mkdocs.yml
Labels: documentation, entrega2
